---
- name: Prepare inventory
  template:
    src: "{{ role_path }}/templates/inventory"
    dest: /inventory
- name: "Checkout ceph playbooks"
  git:
    repo: 'https://github.com/ceph/ceph-ansible.git'
    dest: /playbooks/
    clone: yes
    version: "{{ cephRelease }}"
- name: Prepare ceph deployment configuration
  template:
    src: "{{ role_path }}/templates/group_vars.all.yaml"
    dest: /playbooks/group_vars/all.yaml
- lineinfile:
    path: /etc/ansible/ansible.cfg
    insertafter: '#host_key_checking'
    regexp: '^host_key_checking'
    line: 'host_key_checking = False'
- copy:
    src: id_rsa
    dest: /id_rsa
    mode: 0600
- name: Provision ceph docker via ansible through ansible
  command: /bin/bash -c 'ansible-playbook --key-file "/id_rsa" -i /inventory /playbooks/site.yml.sample | tee /ansible.log '

- name: Provision ceph via ansible through ansible
  command: /bin/bash -c 'ansible-playbook --key-file "/id_rsa" -i /inventory /playbooks/site-docker.yml.sample | tee /ansible.log '
